# Generated by Django 3.1.4 on 2020-12-28 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_from', models.DateTimeField()),
                ('booked_till', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='invited_to', to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.meetingroom')),
            ],
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='reservations',
            field=models.ManyToManyField(through='reservations.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
