# Generated by Django 3.1.4 on 2020-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201228_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
