# Generated by Django 3.1.4 on 2020-12-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_canceled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['username']},
        ),
    ]
